
spring:
  application:
    name: msv-rango-cliente-pdv
  profiles:
    active: dev
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    properties:
      hibernate: 
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: update
    show-sql: true 
  datasource:
    driver-class-name: org.postgresql.Driver
  flyway:
    baseline-on-migrate: true
    
## Topicos Kafka    
topic:
  kafka:
    pedido: TOPICO_PEDIDO   
    grupo:
      id: grupo_pedido
