
CREATE TABLE PRODUTO (
	CODIGO SERIAL NOT NULL CONSTRAINT PK_COD_PRODUTO PRIMARY KEY,
	NOME VARCHAR(30)  NOT NULL,
	DESCRICAO VARCHAR(50)  NOT NULL,
	COD_CATEGORIA INTEGER NOT NULL,
	VALOR  NUMERIC(10,2) NOT NULL,	
	
	CONSTRAINT FK01_PRODUTO_X_CATEGORIA FOREIGN KEY (COD_CATEGORIA) REFERENCES CATEGORIA (CODIGO) 
);