CREATE TABLE USUARIO ( 
	CODIGO SERIAL NOT NULL CONSTRAINT PK_USUARIO PRIMARY KEY, 
	NOME VARCHAR(30) NOT NULL, 
	EMAIL VARCHAR(50) NOT NULL, 
	TELEFONE VARCHAR(20) NOT NULL, 
	SEXO integer NOT NULL
);