CREATE TABLE REGISTRO_PEDIDO ( 
	CODIGO SERIAL NOT NULL CONSTRAINT PK_REGISTRO_PEDIDO PRIMARY KEY,
	COD_STATUS  INTEGER NOT NULL,
	COD_USUARIO  INTEGER NOT NULL,
	DT_SOLICITACAO DATE,
	DT_NOTIFICACAO DATE,
	
	CONSTRAINT FK01_REGISTRO_PEDIDO_X_STATUS_PEDIDO FOREIGN KEY (COD_STATUS) REFERENCES STATUS_PEDIDO (CODIGO),
	CONSTRAINT FK02_REGISTRO_PEDIDO_X_USUARIO FOREIGN KEY (COD_USUARIO) REFERENCES USUARIO (CODIGO) 
);