INSERT INTO STATUS_PEDIDO (CODIGO, DESCRICAO) VALUES(0, 'PEDIDO SOLICITADO');
INSERT INTO STATUS_PEDIDO (CODIGO, DESCRICAO) VALUES(1, 'PEDIDO PENDENTE');
INSERT INTO STATUS_PEDIDO (CODIGO, DESCRICAO) VALUES(2, 'PEDIDO EM PREPARAÇÃO');
INSERT INTO STATUS_PEDIDO (CODIGO, DESCRICAO) VALUES(3, 'PEDIDO ENCAMINHADO');
INSERT INTO STATUS_PEDIDO (CODIGO, DESCRICAO) VALUES(4, 'PEDIDO ENTREGUE');
INSERT INTO STATUS_PEDIDO (CODIGO, DESCRICAO) VALUES(5, 'PEDIDO RECUSADO');